-- Product telemetry for BountyTracker.
-- Run this in the Supabase SQL editor when ready to enable telemetry storage.

create table if not exists public.product_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  path text,
  referrer text,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_product_events_event_name_created_at
  on public.product_events (event_name, created_at desc);

create index if not exists idx_product_events_path_created_at
  on public.product_events (path, created_at desc);

alter table public.product_events enable row level security;

drop policy if exists "product_events_select_none" on public.product_events;

create policy "product_events_select_none"
on public.product_events
for select
using (false);